/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Campeonato;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class Campeonato2023 extends javax.swing.JFrame {

    //Variaveis
    String nome, pais;
    char sexo;
    double altura = 0;

    //Objetos
    Atleta atleta;
    ArrayList geral = new ArrayList();
    Pilha mulheres = new Pilha(1000);
    Queue homens = new Queue();

    public Campeonato2023() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        labelNome = new javax.swing.JLabel();
        paisLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        femininoRadio = new javax.swing.JRadioButton();
        masculinoRadio = new javax.swing.JRadioButton();
        nomeText = new javax.swing.JTextField();
        paisText = new javax.swing.JTextField();
        alturaLabel = new javax.swing.JLabel();
        alturaText = new javax.swing.JTextField();
        ListarCadastroButton = new javax.swing.JButton();
        CadastrarButton = new javax.swing.JButton();
        mediaGeralButton = new javax.swing.JButton();
        mulherMaiorAlturaButton = new javax.swing.JButton();
        mediaHomensBrasileirosButton = new javax.swing.JButton();
        autoresButton = new javax.swing.JButton();
        mostrarPilhaButton = new javax.swing.JButton();
        mostrarFilaButton = new javax.swing.JButton();
        retirarDaPilhaButton = new javax.swing.JButton();
        retirarDaFilaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadoTextArea = new javax.swing.JTextArea();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campeonato2023");

        labelNome.setText("Nome do atleta:");

        paisLabel.setText("Pais:");

        sexoLabel.setText("Sexo:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup3.add(femininoRadio);
        femininoRadio.setText("Feminino");
        femininoRadio.setBorder(new javax.swing.border.MatteBorder(null));
        femininoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femininoRadioActionPerformed(evt);
            }
        });

        buttonGroup3.add(masculinoRadio);
        masculinoRadio.setText("Masculino");
        masculinoRadio.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masculinoRadio)
                    .addComponent(femininoRadio))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(femininoRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masculinoRadio)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        alturaLabel.setText("Altura:");

        ListarCadastroButton.setText("Listar Cadastro");
        ListarCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCadastroButtonActionPerformed(evt);
            }
        });

        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });

        mediaGeralButton.setText("Média Geral");
        mediaGeralButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaGeralButtonActionPerformed(evt);
            }
        });

        mulherMaiorAlturaButton.setText("Mulher maior altura");
        mulherMaiorAlturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulherMaiorAlturaButtonActionPerformed(evt);
            }
        });

        mediaHomensBrasileirosButton.setText("Média homens brasileiros");
        mediaHomensBrasileirosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaHomensBrasileirosButtonActionPerformed(evt);
            }
        });

        autoresButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        autoresButton.setText("Autores");
        autoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoresButtonActionPerformed(evt);
            }
        });

        mostrarPilhaButton.setText("Mostrar pilha");
        mostrarPilhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPilhaButtonActionPerformed(evt);
            }
        });

        mostrarFilaButton.setText("Mostrar fila");
        mostrarFilaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarFilaButtonActionPerformed(evt);
            }
        });

        retirarDaPilhaButton.setText("Retirar da pilha");
        retirarDaPilhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarDaPilhaButtonActionPerformed(evt);
            }
        });

        retirarDaFilaButton.setText("Retirar da fila");
        retirarDaFilaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarDaFilaButtonActionPerformed(evt);
            }
        });

        ResultadoTextArea.setColumns(20);
        ResultadoTextArea.setRows(5);
        jScrollPane1.setViewportView(ResultadoTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paisLabel)
                            .addComponent(sexoLabel)
                            .addComponent(alturaLabel))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(alturaText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ListarCadastroButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(mediaGeralButton)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(retirarDaPilhaButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(retirarDaFilaButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mulherMaiorAlturaButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(mediaHomensBrasileirosButton)
                                        .addGap(50, 50, 50)
                                        .addComponent(autoresButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadastrarButton)
                            .addComponent(labelNome))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(mostrarFilaButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paisText, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(mostrarPilhaButton))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paisLabel)
                    .addComponent(paisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(sexoLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaLabel))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarCadastroButton)
                    .addComponent(mediaGeralButton)
                    .addComponent(mulherMaiorAlturaButton)
                    .addComponent(mediaHomensBrasileirosButton)
                    .addComponent(autoresButton)
                    .addComponent(CadastrarButton))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarPilhaButton)
                    .addComponent(mostrarFilaButton)
                    .addComponent(retirarDaPilhaButton)
                    .addComponent(retirarDaFilaButton))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femininoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femininoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femininoRadioActionPerformed

    private void mostrarPilhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPilhaButtonActionPerformed
        ResultadoTextArea.setText(mulheres.toString());
    }//GEN-LAST:event_mostrarPilhaButtonActionPerformed

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        try {
            nome = nomeText.getText();
            pais = paisText.getText();
            
            //Ifs e Elses para definir as variavel altura
            if (alturaText.getText().equalsIgnoreCase("")) {
                altura = 0;
            } else {
                altura = Double.parseDouble(alturaText.getText());
            }
            
            //if para caso estive algum campo em branco
            if (nome.equalsIgnoreCase("") || pais.equalsIgnoreCase("") || altura == 0) {
                JOptionPane.showMessageDialog(rootPane, "Todos os campos devem ser preechidos");
            }
            
            //Colocando na fila ou na pilha E no ArrayList Geral
            if (buttonGroup3.getSelection()== masculinoRadio.getModel()){
                sexo = 'M';
                atleta = new Atleta(nome, sexo, pais, altura);
                geral.add(atleta);
                homens.enqueue(atleta);
               
            } else if(buttonGroup3.getSelection()== femininoRadio.getModel()){
                sexo = 'F';
                atleta = new Atleta(nome, sexo, pais, altura);
                geral.add(atleta);
                mulheres.push(atleta);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sexo não definido");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Altura deve ser um numerico");
        }

        //Reserta tudo
        nomeText.setText("");
        paisText.setText("");
        alturaText.setText("");
        buttonGroup3.clearSelection();

    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void ListarCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCadastroButtonActionPerformed
        if(geral.isEmpty()){
            ResultadoTextArea.setText("Sem atletas cadastrados");
        }else{
            ResultadoTextArea.setText(geral.toString());
        }
        
    }//GEN-LAST:event_ListarCadastroButtonActionPerformed

    private void mostrarFilaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarFilaButtonActionPerformed
        ResultadoTextArea.setText(homens.toString());
    }//GEN-LAST:event_mostrarFilaButtonActionPerformed

    private void retirarDaPilhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarDaPilhaButtonActionPerformed
        mulheres.pop();
        ResultadoTextArea.setText(mulheres.toString());
    }//GEN-LAST:event_retirarDaPilhaButtonActionPerformed

    private void retirarDaFilaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarDaFilaButtonActionPerformed
        homens.dequeue();
        ResultadoTextArea.setText(homens.toString());
    }//GEN-LAST:event_retirarDaFilaButtonActionPerformed

    private void mediaGeralButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaGeralButtonActionPerformed
        if (geral.isEmpty()) {
            ResultadoTextArea.setText("Sem atletas ainda");
        } else {
            
            double media = 0;
            double aux = 0;
            for (int i = 0; i < geral.size(); i++) {
                Atleta atletaAtual = (Atleta) geral.get(i);
                media += atletaAtual.getAltura();
                aux++;
            }

            media = media / aux;

            ResultadoTextArea.setText("A media geral na altura dos atletas é: " + media);
        }
    }//GEN-LAST:event_mediaGeralButtonActionPerformed

    private void mulherMaiorAlturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulherMaiorAlturaButtonActionPerformed
       if(mulheres.isEmpty()){
       ResultadoTextArea.setText("Sem atletas femininas ainda");
       }else{
        Atleta aMaior=new Atleta("",'F',"",0);
        for(int i = 0 ; i<geral.size();i++){      
            Atleta atletaAtual = (Atleta) geral.get(i);
            if(atletaAtual.getSexo()=='F'){
                if(atletaAtual.getAltura()>aMaior.getAltura()){
                aMaior=atletaAtual;
                }
            }
        }
        ResultadoTextArea.setText(aMaior.toString());
       }
    }//GEN-LAST:event_mulherMaiorAlturaButtonActionPerformed

    private void mediaHomensBrasileirosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaHomensBrasileirosButtonActionPerformed
       if(homens.isEmpty()){
       ResultadoTextArea.setText("Sem atletas masculinos ainda");
       }else{
           double media=0;
           double aux=0;
       for(int i =0 ; i<geral.size();i++){
           Atleta atletaAtual = (Atleta) geral.get(i);
           if(atletaAtual.getSexo()=='M'){
               media+=atletaAtual.getAltura();
               aux++;
           }
       }
       media=media/aux;
       ResultadoTextArea.setText("A media entre os homens é de: "+media);
       }
    }//GEN-LAST:event_mediaHomensBrasileirosButtonActionPerformed

    private void autoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoresButtonActionPerformed
        new Autores().setVisible(true);
    }//GEN-LAST:event_autoresButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Campeonato2023.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Campeonato2023().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JButton ListarCadastroButton;
    private javax.swing.JTextArea ResultadoTextArea;
    private javax.swing.JLabel alturaLabel;
    private javax.swing.JTextField alturaText;
    private javax.swing.JButton autoresButton;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton femininoRadio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JRadioButton masculinoRadio;
    private javax.swing.JButton mediaGeralButton;
    private javax.swing.JButton mediaHomensBrasileirosButton;
    private javax.swing.JButton mostrarFilaButton;
    private javax.swing.JButton mostrarPilhaButton;
    private javax.swing.JButton mulherMaiorAlturaButton;
    private javax.swing.JTextField nomeText;
    private javax.swing.JLabel paisLabel;
    private javax.swing.JTextField paisText;
    private javax.swing.JButton retirarDaFilaButton;
    private javax.swing.JButton retirarDaPilhaButton;
    private javax.swing.JLabel sexoLabel;
    // End of variables declaration//GEN-END:variables
}
